# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: rest-read-module
  labels:
    name: rest-read-module
    version: 0.0.1  # semantic version
  namespace: fybrik-system
spec:
  type: service
  capabilities:
    - capability: read
      actions:
        - name: Policies
      api:
        connection:
          name: rest-read
          rest-read:
            port: 5559
        dataFormat: json
      supportedInterfaces:
        - source:
            protocol: rest
            dataformat: json
  chart:
    name: ghcr.io/fybrik/rest_dashboard_chart:0.1.0
    values:
      image.tag: 0.0.2
  statusIndicators:
    - kind: StreamTransfer
      successCondition: status.status == SUCCEEDED
      failureCondition: status.status == FAILED
      errorMessage: status.error
