apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: api.personnel-data.get-safety-data
  namespace: fogprotect
spec:
  details: 
    dataFormat: json
    connection:
      name: rest
      rest:
        endpoint: "http://127.0.0.1:5559/api/personnel_data/get_safety_data"
  secretRef:
    name: ""
  metadata:
    name: REST server
    tags:
      personnel: true
    columns:
      - name: production_sector.with_helmet
        tags:
          PII: true
      - name: production_sector.without_helmet
        tags:
          PII: true
      - name: production_sector.total
        tags:
          sensitive: true
      - name: non_production_sector.with_helmet
        tags:
          PII: true
      - name: non_production_sector.without_helmet
        tags:
          PII: true
      - name: non_production_sector.total
        tags:
          PII: sensitive
      - name: full_area.with_helmet
        tags:
          PII: true
      - name: full_area.without_helmet
        tags:
          PII: true
      - name: full_area.total
        tags:
          sensitive: true
