apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: api.data.get-occupancy
spec:
  secretRef:
    name: ""
  assetDetails:
    dataFormat: csv
    connection:
      type: s3
      s3:
        endpoint: "http://127.0.0.1:5559/api/data/get_occupancy"
        bucket: demo
        objectKey: "hello"
  assetMetadata:
    tags:
    - data
    componentsMetadata:
      occupancy:
        tags:
        - occupancy_related
      Age:
        tags:
        - PII
      Lname:
        tags:
        - sensitive
