apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: api.control.stop-robot
spec:
  secretRef:
    name: ""
  assetDetails:
    dataFormat: csv
    connection:
      type: s3
      s3:
        endpoint: "http://127.0.0.1:5559/api/control/stop_robot"
        bucket: demo
        objectKey: "hello"
  assetMetadata:
    tags:
    - control
    componentsMetadata:
      id:
        tags:
        - PII
      Age:
        tags:
        - sensitive
      Lname:
        tags:
        - sensitive
