apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: api.control.start-robot
  namespace: fogprotect
spec:
  secretRef:
    name: ""
  details:
    dataFormat: json
    connection:
      name: rest
      rest:
        endpoint: "http://127.0.0.1:5559/api/control/start_robot"
  metadata:
    name: robot
    tags:
      control: true
    columns:
      - name: id
        tags:
          PII: true
      - name: Age
        tags:
          PII: true
      - name: Lname
        tags:
          sensitive: true
