apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: api.data.get-occupancy
  namespace: fogprotect
spec:
  secretRef:
    name: ""
  details:
    dataFormat: csv
    connection:
      name: rest
      rest:
        endpoint: "http://127.0.0.1:5559/api/data/get_occupancy"
  metadata:
    tags:
      occupancy_related: true   
    columns:
      - name: Age
        tags:
          PII: true
      - name: Lname
        tags:
          sensitive: true
