apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: api.data.read-data
  namespace: fogprotect
spec:
  details:
    dataFormat: json
    connection:
      name: rest
      rest:
        endpoint: "http://127.0.0.1:5559/api/data/read_data"
  secretRef:
    name: ""
  metadata:
    name: REST server
    tags: 
      data: true
    columns:
      - name: sensors
        tags:
          PII: true
      - name: Age
        tags:
          PII: true
      - name: Lname
        tags:
          sensitive: true
